// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package test_user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// user info
type User struct {
	FirstName            string         `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string         `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Sex                  string         `protobuf:"bytes,3,opt,name=sex,proto3" json:"sex,omitempty"`
	Email                string         `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Location             *User_Location `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetLocation() *User_Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type User_Location struct {
	State                string   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Ciry                 string   `protobuf:"bytes,2,opt,name=ciry,proto3" json:"ciry,omitempty"`
	Street               string   `protobuf:"bytes,3,opt,name=street,proto3" json:"street,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User_Location) Reset()         { *m = User_Location{} }
func (m *User_Location) String() string { return proto.CompactTextString(m) }
func (*User_Location) ProtoMessage()    {}
func (*User_Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0, 0}
}

func (m *User_Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_Location.Unmarshal(m, b)
}
func (m *User_Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_Location.Marshal(b, m, deterministic)
}
func (m *User_Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_Location.Merge(m, src)
}
func (m *User_Location) XXX_Size() int {
	return xxx_messageInfo_User_Location.Size(m)
}
func (m *User_Location) XXX_DiscardUnknown() {
	xxx_messageInfo_User_Location.DiscardUnknown(m)
}

var xxx_messageInfo_User_Location proto.InternalMessageInfo

func (m *User_Location) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *User_Location) GetCiry() string {
	if m != nil {
		return m.Ciry
	}
	return ""
}

func (m *User_Location) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

// get users
type UsersRequest struct {
	// number of users requested
	ResultCount          int32    `protobuf:"varint,1,opt,name=resultCount,proto3" json:"resultCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersRequest) Reset()         { *m = UsersRequest{} }
func (m *UsersRequest) String() string { return proto.CompactTextString(m) }
func (*UsersRequest) ProtoMessage()    {}
func (*UsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *UsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersRequest.Unmarshal(m, b)
}
func (m *UsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersRequest.Marshal(b, m, deterministic)
}
func (m *UsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersRequest.Merge(m, src)
}
func (m *UsersRequest) XXX_Size() int {
	return xxx_messageInfo_UsersRequest.Size(m)
}
func (m *UsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersRequest proto.InternalMessageInfo

func (m *UsersRequest) GetResultCount() int32 {
	if m != nil {
		return m.ResultCount
	}
	return 0
}

// return list of users
type UsersReply struct {
	// list of users
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersReply) Reset()         { *m = UsersReply{} }
func (m *UsersReply) String() string { return proto.CompactTextString(m) }
func (*UsersReply) ProtoMessage()    {}
func (*UsersReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *UsersReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersReply.Unmarshal(m, b)
}
func (m *UsersReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersReply.Marshal(b, m, deterministic)
}
func (m *UsersReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersReply.Merge(m, src)
}
func (m *UsersReply) XXX_Size() int {
	return xxx_messageInfo_UsersReply.Size(m)
}
func (m *UsersReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersReply.DiscardUnknown(m)
}

var xxx_messageInfo_UsersReply proto.InternalMessageInfo

func (m *UsersReply) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "test_user.User")
	proto.RegisterType((*User_Location)(nil), "test_user.User.Location")
	proto.RegisterType((*UsersRequest)(nil), "test_user.UsersRequest")
	proto.RegisterType((*UsersReply)(nil), "test_user.UsersReply")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xcf, 0x4a, 0xf3, 0x50,
	0x10, 0xc5, 0x49, 0xdb, 0x94, 0x74, 0xfa, 0xfd, 0x63, 0xf8, 0xd4, 0x10, 0xba, 0x08, 0x01, 0xa1,
	0xab, 0x54, 0x5a, 0xdf, 0x40, 0x57, 0x52, 0x5c, 0x04, 0x04, 0x77, 0x72, 0x2d, 0x63, 0xb9, 0x70,
	0x9b, 0x1b, 0xef, 0x4c, 0xc4, 0x6e, 0x7d, 0x05, 0x1f, 0xcd, 0x57, 0x70, 0xe9, 0x43, 0x48, 0x6e,
	0xd2, 0x2a, 0x75, 0x77, 0xcf, 0x39, 0x33, 0x67, 0x7e, 0x21, 0xf0, 0x9b, 0xc9, 0x3d, 0xe9, 0x15,
	0xe5, 0x95, 0xb3, 0x62, 0x71, 0x24, 0xc4, 0x72, 0x57, 0x33, 0xb9, 0x64, 0xb2, 0xb6, 0x76, 0x6d,
	0x68, 0xa6, 0x2a, 0x3d, 0x53, 0x65, 0x69, 0x45, 0x89, 0xb6, 0x25, 0xb7, 0x83, 0xd9, 0x47, 0x00,
	0x83, 0x1b, 0x26, 0x87, 0x13, 0x18, 0x3d, 0x68, 0xc7, 0x72, 0xad, 0x36, 0x14, 0x07, 0x69, 0x30,
	0x1d, 0x15, 0x5f, 0x06, 0x26, 0x10, 0x19, 0xd5, 0x85, 0x3d, 0x1f, 0xee, 0x35, 0xfe, 0x83, 0x3e,
	0xd3, 0x73, 0xdc, 0xf7, 0x76, 0xf3, 0xc4, 0xff, 0x10, 0xd2, 0x46, 0x69, 0x13, 0x0f, 0xbc, 0xd7,
	0x0a, 0x3c, 0x87, 0xc8, 0xd8, 0x95, 0xbf, 0x1e, 0x87, 0x69, 0x30, 0x1d, 0xcf, 0xe3, 0x7c, 0x8f,
	0x99, 0x37, 0x10, 0xf9, 0xb2, 0xcb, 0x8b, 0xfd, 0x64, 0xb2, 0x84, 0x68, 0xe7, 0x36, 0xbd, 0x2c,
	0x4a, 0x76, 0x7c, 0xad, 0x40, 0x84, 0xc1, 0x4a, 0xbb, 0x6d, 0xc7, 0xe5, 0xdf, 0x78, 0x0c, 0x43,
	0x16, 0x47, 0x24, 0x1d, 0x56, 0xa7, 0xb2, 0x33, 0xf8, 0xd5, 0x1c, 0xe2, 0x82, 0x1e, 0x6b, 0x62,
	0xc1, 0x14, 0xc6, 0x8e, 0xb8, 0x36, 0x72, 0x61, 0xeb, 0x52, 0x7c, 0x6f, 0x58, 0x7c, 0xb7, 0xb2,
	0x05, 0x40, 0xb7, 0x51, 0x99, 0x2d, 0x9e, 0x42, 0xd8, 0xd0, 0x72, 0x1c, 0xa4, 0xfd, 0xe9, 0x78,
	0xfe, 0xf7, 0xe0, 0x03, 0x8a, 0x36, 0x9d, 0xdf, 0xb6, 0x4b, 0x97, 0x76, 0xa3, 0x74, 0x89, 0x57,
	0x10, 0xad, 0x49, 0x7c, 0x0b, 0x9e, 0x1c, 0x6c, 0xec, 0x48, 0x92, 0xa3, 0x9f, 0x41, 0x65, 0xb6,
	0xd9, 0x9f, 0x97, 0xb7, 0xf7, 0xd7, 0x5e, 0x84, 0xc3, 0x99, 0x6f, 0xbe, 0x1f, 0xfa, 0xdf, 0xb6,
	0xf8, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x27, 0x11, 0x4e, 0x0f, 0xf0, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserDomainClient is the client API for UserDomain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserDomainClient interface {
	GetUsers(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (*UsersReply, error)
}

type userDomainClient struct {
	cc *grpc.ClientConn
}

func NewUserDomainClient(cc *grpc.ClientConn) UserDomainClient {
	return &userDomainClient{cc}
}

func (c *userDomainClient) GetUsers(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (*UsersReply, error) {
	out := new(UsersReply)
	err := c.cc.Invoke(ctx, "/test_user.UserDomain/getUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserDomainServer is the server API for UserDomain service.
type UserDomainServer interface {
	GetUsers(context.Context, *UsersRequest) (*UsersReply, error)
}

// UnimplementedUserDomainServer can be embedded to have forward compatible implementations.
type UnimplementedUserDomainServer struct {
}

func (*UnimplementedUserDomainServer) GetUsers(ctx context.Context, req *UsersRequest) (*UsersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}

func RegisterUserDomainServer(s *grpc.Server, srv UserDomainServer) {
	s.RegisterService(&_UserDomain_serviceDesc, srv)
}

func _UserDomain_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test_user.UserDomain/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainServer).GetUsers(ctx, req.(*UsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserDomain_serviceDesc = grpc.ServiceDesc{
	ServiceName: "test_user.UserDomain",
	HandlerType: (*UserDomainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getUsers",
			Handler:    _UserDomain_GetUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
